print(getwd())
print("----------------------------")
print(head(iris))
print("----------------------------")
print(head(x=iris, n=2))
print("----------------------------")
print(head(iris,2))
print("----------------------------")